# Generated by Django 4.2.6 on 2023-10-27 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wink', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
