# Generated by Django 4.2.6 on 2023-10-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wink', '0002_remove_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pw',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
